import re
from typing import Any

VULNERABILITY_PATTERNS = [
    {
        "name": "Reentrancy via msg.sender.call",
        "pattern": re.compile(r"\bmsg\.sender\s*\.\s*call\b"),
        "severity": "critical",
        "impact": "Attacker-controlled target may reenter the contract state and drain funds.",
        "poc": "Avoid low-level calls to msg.sender. Use pull payments or reentrancy guards and checks-effects-interactions.",
    },
    {
        "name": "tx.origin authorization",
        "pattern": re.compile(r"\btx\.origin\b"),
        "severity": "critical",
        "impact": "Authorization using tx.origin can be bypassed through malicious contract forwarding.",
        "poc": "Replace tx.origin logic with msg.sender and dedicated role-based access control.",
    },
    {
        "name": "Unchecked math operation",
        "pattern": re.compile(r"\bunchecked\b|\buint(?:256)?\s+\w+\s*=\s*[^;]+[+\-*/%][^;]+;"),
        "severity": "high",
        "impact": "Arithmetic without overflow safety can lead to incorrect balances or underflows.",
        "poc": "Use built-in Solidity overflow checks or wrap critical operations in explicit validations.",
    },
]


def _find_line_numbers(code: str, regex: re.Pattern) -> list[int]:
    return [
        idx + 1
        for idx, line in enumerate(code.splitlines())
        if regex.search(line)
    ]


def analyze_vulnerabilities(code: str) -> dict[str, Any]:
    findings: list[dict[str, Any]] = []
    for pattern in VULNERABILITY_PATTERNS:
        lines = _find_line_numbers(code, pattern["pattern"])
        if not lines:
            continue

        for line_number in lines:
            findings.append(
                {
                    "name": pattern["name"],
                    "line": line_number,
                    "severity": pattern["severity"],
                    "impact": pattern["impact"],
                    "poc": pattern["poc"],
                    "pattern": pattern["pattern"].pattern,
                }
            )

    if not findings:
        summary = "No critical or high-risk patterns detected. Manual review still recommended."
    else:
        summary = f"{len(findings)} issue(s) detected. Prioritize critical and high severity findings."

    return {
        "summary": summary,
        "findings": findings,
        "analysis_metrics": {
            "issue_count": len(findings),
            "critical": sum(1 for f in findings if f["severity"] == "critical"),
            "high": sum(1 for f in findings if f["severity"] == "high"),
        },
    }


def generate_immunefi_markdown(report: dict[str, Any], contract_name: str = "SolidityContract") -> str:
    header = f"# Immunefi Bug Bounty Report - {contract_name}\n\n"
    header += "## Executive Summary\n"
    header += f"{report['summary']}\n\n"
    header += "## Findings\n"

    if not report["findings"]:
        header += "- No automated high-risk patterns were discovered. Continue manual review and dynamic testing.\n\n"
    else:
        for finding in report["findings"]:
            header += f"### {finding['name']}\n"
            header += f"- Severity: **{finding['severity'].upper()}**\n"
            header += f"- Line: {finding['line']}\n"
            header += f"- Impact: {finding['impact']}\n"
            header += f"- PoC recommendation: {finding['poc']}\n\n"

    header += "## Recommendations\n"
    header += "- Introduce reentrancy guards and avoid low-level external calls to untrusted addresses.\n"
    header += "- Replace tx.origin-based access control with role-based checks using msg.sender.\n"
    header += "- Validate arithmetic operations and avoid unchecked blocks on security-critical paths.\n"
    header += "\n## Notes\n"
    header += "This report was generated by RainSoul258Studios Infinity 02 using static analysis and pattern matching. Manual and dynamic analysis should be performed for a complete security assessment.\n"
    return header
